import gdspy
import math

def count_qr_codes(gds_file):
    """For a given gds file (generated by our QR file generator)
    , reads the file and gets all the dependencies of the file
    """
    # Load the GDS file
    library = gdspy.GdsLibrary()
    library.read_gds(gds_file)

    # Get the top level cell (parent of all other cells)
    top_cell = library.top_level()[0]

    # get a list of all the cells
    all_cells = list(top_cell.get_dependencies())
    n = len(all_cells)
    length, height = top_cell.get_bounding_box()[1]
    qr_size = all_cells[0].get_bounding_box()[1][0] - all_cells[0].get_bounding_box()[0][0]
    # gets the length of the rows/cols in terms of the qr size
    row_length = length / qr_size
    col_length = height / qr_size
    #standardizes these sizes to get the actual number of qrs in each row/col
    qrs_in_row, qrs_in_col = scale_to_product(row_length, col_length, n)
    qrs_in_row, qrs_in_col = round(qrs_in_row), round(qrs_in_col)
    return (n, qr_size.item(), qrs_in_row, qrs_in_col)


def scale_to_product(a, b, target_product):
    """Returns a scaled a and b such that a * b = target_product"""
    current_product = a * b
    scaling_factor = (target_product/current_product) ** .5
    return a * scaling_factor, b * scaling_factor

# Example usage
if __name__ == "__main__":
    gds_file_path = "file.gds"  # Replace with your .gds file path
    qr_code_count = count_qr_codes(gds_file_path)
    print(f"Number of QR codes in the GDS file: {qr_code_count}")