# Generated by Django 5.1.5 on 2025-01-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gds_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('num_qrs', models.IntegerField()),
                ('qr_size', models.FloatField()),
                ('qrs_per_row', models.IntegerField()),
                ('qrs_per_col', models.IntegerField()),
                ('time_uploaded', models.CharField(max_length=50)),
                ('last_updated', models.CharField(max_length=50)),
            ],
        ),
    ]
