# Generated by Django 5.1.5 on 2025-01-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gds_file_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=50)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('abs_x', models.FloatField()),
                ('abs_y', models.FloatField()),
                ('num_codes', models.IntegerField()),
                ('img_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='gds_files',
            name='padding',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gds_files',
            name='spacing',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
