# Generated by Django 5.1.5 on 2025-02-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sample_images_gds_files_padding_gds_files_spacing'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_images',
            name='is_anchor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
