# Generated by Django 5.1.5 on 2025-02-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sample_images_is_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_images',
            name='layer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
